language: java
jdk:
  - oraclejdk8
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
        - 0.5-branch
notifications:
    email:
        recipients:
        - pholser@alumni.rice.edu

