language: java
jdk:
    - oraclejdk8
install: mvn install -DskipTests=true -Dcobertura.skip -Dmaven.javadoc.skip=true -B -V
script: mvn clean test -Dcobertura.skip=true
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
        - 0.5-branch
notifications:
    email:
        recipients:
        - pholser@alumni.rice.edu

