language: java
sudo: no
jdk:
  - oraclejdk8
install:
  - "mvn -N -q io.takari:maven:wrapper -Dmaven=3.3.9"
script: './mvnw --show-version --errors --batch-mode clean verify'
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
        - 0.5-branch
notifications:
    email:
        recipients:
        - pholser@alumni.rice.edu

